server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cj6m6mmym46v.ap-northeast-2.rds.amazonaws.com:3306/db_project2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: sa
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 이미지 업로드 경로 설정 추가 (Docker 볼륨 경로)
image:
  upload:
    dir: /app/images
