server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cj6m6mmym46v.ap-northeast-2.rds.amazonaws.com:3306/db_project2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: sa
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB