name: Docker Image Delivery

on:
  workflow_dispatch:

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      # 이미지 태그 설정
      - name: Set Image Tag
        id: image-tag
        run: echo "TAG=$(date +%s)-ci" >> "$GITHUB_OUTPUT"
      # Docker Build
      - name: Build the Docker image
        env:
          TAG: ${{ steps.image-tag.outputs.TAG }}
        run: docker build --file Dockerfile --tag "${{ secrets.DOCKERHUB_USERNAME }}/ec_mall-boot:$TAG" .
      - name: Longin To Docker Hub
#        run: echo "password" docker login -u username --password-stdin
        uses: docker/login-action@v3
        with:
          # 외부에 공개되면 안되는 정보를 GitHub의 Secrets and Variables에 저장
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Docker Image
        env:
          TAG: ${{ steps.image-tag.outputs.TAG }}
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/ec_mall-boot:$TAG"
      # latest push 하기
      - name: Tag Image as latest
        env:
          TAG: ${{ steps.image-tag.outputs.TAG }}
        run: |
          docker tag "${{ secrets.DOCKERHUB_USERNAME }}/ec_mall-boot:$TAG" \
          "${{ secrets.DOCKERHUB_USERNAME }}/ec_mall-boot:latest"
      - name: Push latest
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/ec_mall-boot:latest"

      # AWS
      # AWS 로그인
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      # CodeDeploy 실행
      - name: Create Deployment
        run: |
          aws deploy create-deployment \
          --cli-input-json file://./code-deploy.json \
          --region ap-northeast-2