name: Docker Image Delivery

on:
  workflow_dispatch:

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      # 이미지 태그 설정
      - name: Set Image Tag
        id: image-tag
        run: echo "TAG=$(date +%s)-ci" >> "$GITHUB_OUTPUT"
      # Docker Build
      - name: Build the Docker image
        env:
          TAG: ${{ steps.image-tag.outputs.TAG }}
        run: docker build --file Dockerfile --tag "wlsdud0/ec_mall-boot:$TAG" .
      - name: Longin To Docker Hub
#        run: echo "password" docker login -u username --password-stdin
        uses: docker/login-action@v3
        with:
          # 외부에 공개되면 안되는 정보를 GitHub의 Secrets and Variables에 저장
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Docker Image
        env:
          TAG: ${{ steps.image-tag.output.TAG }}
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/ec_mall-boot:$TAG"